// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYJl4k6VtfLVt8ciq_vzcwrd5JAyZQQPM',
    appId: '1:880790415520:web:fd8d7388154de08b0901c5',
    messagingSenderId: '880790415520',
    projectId: 'sleep-apnea-21cc3',
    authDomain: 'sleep-apnea-21cc3.firebaseapp.com',
    databaseURL: 'https://sleep-apnea-21cc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-apnea-21cc3.appspot.com',
    measurementId: 'G-JNSF8X1SGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBy2969Zej0bMtJd50GsyIKX3GY-_Fb8fc',
    appId: '1:880790415520:android:6cd5786be7a1ca060901c5',
    messagingSenderId: '880790415520',
    projectId: 'sleep-apnea-21cc3',
    databaseURL: 'https://sleep-apnea-21cc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-apnea-21cc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCABLMxfsVTAu8_L9W0_B-4iSwfDEQVkgQ',
    appId: '1:880790415520:ios:a16477b158e60dde0901c5',
    messagingSenderId: '880790415520',
    projectId: 'sleep-apnea-21cc3',
    databaseURL: 'https://sleep-apnea-21cc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-apnea-21cc3.appspot.com',
    iosClientId: '880790415520-k3kftdcc9bu6hft45diaguuhosupsusq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCABLMxfsVTAu8_L9W0_B-4iSwfDEQVkgQ',
    appId: '1:880790415520:ios:a16477b158e60dde0901c5',
    messagingSenderId: '880790415520',
    projectId: 'sleep-apnea-21cc3',
    databaseURL: 'https://sleep-apnea-21cc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleep-apnea-21cc3.appspot.com',
    iosClientId: '880790415520-k3kftdcc9bu6hft45diaguuhosupsusq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
